
const Images = {
    profile: require('./profile.jpg').default,
    Market: require('./cart.png').default,
    Form: require('./form.png').default,
    information: require('./information.png').default,
    hashtag: require('./hashtag.png').default,
    SeedIcon: require('./seed.png').default,
    Warehouse: require('./wearhouse.png').default,
    Cow: require('./cow.png').default,
    Pesticide: require('./pesticide.png').default,
    Tractor: require('./tractor.png').default,
    Cultivator: require('./cultivator.png').default,
    Vegetables: require('./vegetables.png').default,
    LightBulb: require('./lightBulb.png').default,
    Buffalo: require('./buffalo.png').default,
    Goat: require('./goat.png').default,
    Hen: require('./hen.png').default,
    cowSell: require('./cowSell.png').default,
    Dog: require('./dog.png').default,
    bull: require('./Bull.png').default,
    buffaloBull: require('./buffaloBull.png').default,
    goatMale: require('./goatMale.png').default,
}
export default Images;